name: Sync Google Sheets to GitHub

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync-sheets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install gspread pandas oauth2client

    - name: Download Google Sheets as CSV
      run: |
        python -c "
import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials
import os

# Use Google Sheets API without authentication for public sheets
gc = gspread.service_account(filename='credentials.json')

# Your Google Sheets ID
SHEET_ID = '19sJ9V-kYI_BAcctQzJwz5-7mYbyZEmpxm9e3I2dDBOg'

try:
    # Try to open without auth first (for public sheets)
    sh = gc.open_by_key(SHEET_ID)
except:
    # If that fails, the sheet might be private
    print('Sheet might be private or not found')
    exit(1)

# Get the first worksheet
worksheet = sh.sheet1

# Get all data
data = worksheet.get_all_records()

# Convert to DataFrame and save as CSV
df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)
print(f'Successfully downloaded {len(data)} records')
"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update data from Google Sheets"
        git push
